name: Push Setup Code

on:
  workflow_dispatch:

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate project structure
        run: |
          mkdir frontend
          cd frontend
          npm create vite@latest . -- --template react
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss init -p
          echo -e "@tailwind base;\n@tailwind components;\n@tailwind utilities;" > src/index.css

          cd ..
          mkdir backend
          cd backend
          npm init -y
          npm install express cors dotenv pg
          echo 'const express = require("express"); const app = express(); app.use(require("cors")()); app.use(express.json()); app.get("/", (req, res) => res.send("API Running")); app.listen(4000, () => console.log("Server on 4000"));' > index.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b setup
          git add .
          git commit -m "Automated setup: frontend/backend scaffolding"
          git push origin setup --force
